dataset = "JOB"
duckdb_database = "data/duckdb/JOB/job.db"
output_folder = "data/generated_queries/synthetic_queries/Job"
histogram_path = "data/histograms/histogram_job.parquet"

unique_joins = true
max_signatures_per_fact_table = 30
max_queries_per_signature = 50

max_hops = [2,3]
keep_edge_probability = [0.2]

extra_predicates = [2,3,4]
row_retention_probability = [0.2,0.3,0.5,0.8]
equality_lower_bound_probability = [0.5,0.1,0.01,0]
extra_values_for_in = 4

[operator_weights]
operator_in = 2
operator_range = 4
operator_equal = 5