dataset = "TPCDS"
duckdb_database = "data/duckdb/TPCDS/0.1.db"
output_folder = "data/generated_queries/synthetic_queries/TPC_DS"

unique_joins = true
max_queries_per_fact_table = 10
max_queries_per_signature = 2

max_hops = [1,2,4]
keep_edge_probability = [0.2]

extra_predicates = [1,3,5]
row_retention_probability = [0.2, 0.85,1.0]
equality_lower_bound_probability = [0,0.1]
extra_values_for_in = 3

[operator_weights]
operator_in = 1
operator_range = 3
operator_equal = 3