input_parquet = "/home/mathos/phd/repos/query_generation/trunk/data/generated_queries/SNOWFLAKE_SEARCH_PARAMS/JOB/JOB_batches.parquet"
destination_folder = "/home/mathos/phd/repos/query_generation/trunk/data/generated_queries/SNOWFLAKE_SEARCH_PARAMS/FILTER_JOB"
filter_null  = true
cherry_pick = true

[cherry_pick_config]
queries_per_bin = 1
upper_bound = 1000000
total_bins = 2
