dataset = "JOB"
dev = true
max_hops = [1]
extra_predicates = [2,3,4]
row_retention_probability = [0.2]
unique_joins = true
max_queries_per_fact_table = 10
max_queries_per_signature = 1
keep_edge_probability = 0.8
equality_lower_bound_probability = [0]
extra_values_for_in = 3

[operator_weights]
operator_in = 3
operator_range = 2
operator_equal = 5