dataset = "TPCDS"
dev = true
max_hops = [1]
extra_predicates = [1]
row_retention_probability = [0.2, 0.9]
unique_joins = true
max_queries_per_fact_table = 1
max_queries_per_signature = 2
keep_edge_prob = 0.2

[operator_probabilities]
operator_in = 1
operator_range = 3
operator_equal = 3