# Dataset for accesssing the histograms
dataset = "TPCDS"
# Max ammounts of hops for the subgraph generation
max_hops = 3
# Total amount of queries for each fact table in each batch
max_queries_per_fact_table = 100
# Total amount of query signature for each fact table in each batch
max_queries_per_signature = 1
# probability to keep an edge when generating a subgraph
keep_edge_probability = 0.2



[predicate_parameters]
# minimum probability to aim for when doing a range predicate
# using histograms to estimate the selectivity
row_retention_probability = 0.2
# minimum probability to keep an element in the IN-statement
# or = statement
equality_lower_bound_probability = 0.01
# number of values in the IN-statement
extra_values_for_in = 3
# number of extra predicates to add
extra_predicates = 3

# weights to choose operators when selecting a random operator
[predicate_parameters.operator_weights]
operator_in = 1
operator_range = 3
operator_equal = 3