# Inputs
queries_folder = "generated_data/TPCH/extended_queries_ollama/"
# Outputs
destination_folder = "generated_data/TPCH/transformed_queries_ollama/"
# Parameters
max_output_size = 100
timeout_seconds = 15

[engine]
database_path = "generated_data/TPCH/database/TPCH_0.1.duckdb"
validator_engine = "duckdb"
