dataset = "TPCDS"
duckdb_database = "generated_data/TPCDS_100/database/TPCDS_100.duckdb"
output_folder = "generated_data/TPCDS_100/synthetic_data/"
histogram_path = "generated_data/TPCDS_100/histograms/histogram.parquet"

unique_joins = true
max_signatures_per_fact_table = 10
max_queries_per_signature = 2

max_hops = [1,2,4]
keep_edge_probability = [0.2]

extra_predicates = [1,3,5]
row_retention_probability = [0.2, 0.85,1.0]
equality_lower_bound_probability = [0,0.1]
extra_values_for_in = 3

[operator_weights]
operator_in = 1
operator_range = 3
operator_equal = 3