llm_extension = true
union_extension = true
queries_parquet = "tmp/filtered_queries/filtered.parquet"
destination_folder = "tmp/extended_queries_ollama"

[union_params]
max_queries = 5
probability = 0.7

[llm_params]
provider = "ollama"
model = "llama3:latest"
retry = 0
total_queries = 7

[llm_params.engine_params]
database_path = "tmp/database_TPCDS_0.1.duckdb"
validator_engine = "duckdb"
validation_timeout_seconds = 20.0
prompts_path = "params_config/prompts/basic_prompt.toml"
schema_path = "params_config/schemas/dev.txt"
function_examples_path = "params_config/functions/standard_sql_functions.toml"
number_of_function_examples = 5
