llm_extension = true
union_extension = false
queries_parquet = "tmp/filtered_queries/filtered.parquet"
destination_folder = "tmp/extended_queries_batch"

[llm_params]
provider = "openai"
model = "gpt-4o-mini"
batch_size = 100
batch_poll_interval_seconds = 30.0
database_path = "tmp/database_TPCDS_0.1.duckdb"
retry = 1
total_queries = 100
prompts_path = "params_config/prompts/basic_prompt.toml"
schema_path = "params_config/schemas/dev.txt"
function_examples_path = "params_config/functions/standard_sql_functions.toml"
number_of_function_examples = 5
