llm = false
llm_model = "deepseek-r1:70b"
llm_base_prompt = """
    You are a database expert. And you are writing \
    queries to test your current database with the TPCDS \
    dataset with challenging and diverse queries. You are \
    currently re-writing new queries that should not be \
    trivial or equivalent to the input query.
    """
queries_path = "./data/generated_queries/TPCDS_FORMATTED_QUERIES"
total_queries = 5
seed = 42
dataset = "TPCDS"
destination_folder = "./data/generated_queries/TPCDS_LLM"

[llm_prompts.self_join]
prompt = "Modify this query to add a self-join while keeping the predicates"
weight = 30

[llm_prompts.outer_join]
prompt = "Modify this query to add an outer-join while keeping the predicates"
weight = 30